##################################################################################################################################
#                                                                                                                                #
#  Name Script: ConvertRosettaPdbB2WOW.mcr                                                                                       #
#               --------------------------                                                                                       #       
#                                                                                                                                #
#                                                                                                                                #
#  Purpose:     Convert a AT file just generated by Roseta with correct conformations in subunit A to one ready for calculations #
#               in subunit B                                                                                                     #
#                                                                                                                                #
#  Author:      Hein J. Wijma, H.J.Wijma@rug.nl                                                                                  #  
#                                                                                                                                #
#  Usage:       yasara -txt AT_ConvertRosettaPdbB2WOW.mcr                                                                        #
#                                                                                                                                #
#  Further:     From Mac TextWrangler: set under preferences -> Appearances _> page guide at 130; under printing set custom font #
#               to courier-7, for easy printing. On screen can be 13 (view).                                                     #
#                                                                                                                                #
#  Issues:      In some rare cases, the PLP ring ends up not being aromatic. E.g., ligand 47R and 48R                            #
#                                                                                                                                #
##################################################################################################################################

DELOBJ all


# load the scaffold protein for the water molecules
LOADPDB (Scaffold)

# load the design after calculations on subunit A for how the PMP in subunit A is bound
LOADPDB (MacroTargetA)

# do an alignment, object 1 to object 2
ALIGNOBJ 1,2, method = globalseq

# now from the scaffold remove everything except the water, from OBJ 2 only keep the cofactor. 
DELRES OBJ 1 res !HOH
DELRES OBJ 2 res protein

#load the design after calculations on subunit B for the rest (protein, pmp intermediate in subunit B). 
LOADPDB (MacroTargetB)

# add the cofactor and water to the final docked structure. 
JOINOBJ 2,3
JOINOBJ 1,3




# colours are initialized as two enormous list of colours and codes. This way they can systematically be defined. 
ListColours() = 'indian_red','crimson','lightpink','lightpink_1','lightpink_2','lightpink_3','lightpink_4','pink','pink_1','pink_2','pink_3','pink_4','palevioletred','palevioletred_1','palevioletred_2','palevioletred_3','palevioletred_4','lavenderblush_1','lavenderblush','lavenderblush_2','lavenderblush_3','lavenderblush_4','violetred_1','violetred_2','violetred_3','violetred_4','hotpink','hotpink_1','hotpink_2','hotpink_3','hotpink_4','raspberry','deeppink_1','deeppink','deeppink_2','deeppink_3','deeppink_4','maroon_1','maroon_2','maroon_3','maroon_4','mediumvioletred','violetred','orchid','orchid_1','orchid_2','orchid_3','orchid_4','thistle','thistle_1','thistle_2','thistle_3','thistle_4','plum_1','plum_2','plum_3','plum_4','plum','violet','magenta','fuchsia','magenta_2','magenta_3','darkmagenta','magenta_4','purple','mediumorchid','mediumorchid_1','mediumorchid_2','mediumorchid_3','mediumorchid_4','darkviolet','darkorchid','darkorchid_1','darkorchid_2','darkorchid_3','darkorchid_4','indigo','blueviolet','purple_1','purple_2','purple_3','purple_4','mediumpurple','mediumpurple_1','mediumpurple_2','mediumpurple_3','mediumpurple_4','darkslateblue','lightslateblue','mediumslateblue','slateblue','slateblue_1','slateblue_2','slateblue_3','slateblue_4','ghostwhite','lavender','blue','blue_2','blue_3','mediumblue','darkblue','blue_4','navy','midnightblue','cobalt','royalblue','royalblue_1','royalblue_2','royalblue_3','royalblue_4','cornflowerblue','lightsteelblue','lightsteelblue_1','lightsteelblue_2','lightsteelblue_3','lightsteelblue_4','lightslategray','slategray','slategray_1','slategray_2','slategray_3','slategray_4','dodgerblue_1','dodgerblue','dodgerblue_2','dodgerblue_3','dodgerblue_4','aliceblue','steelblue','steelblue_1','steelblue_2','steelblue_3','steelblue_4','lightskyblue','lightskyblue_1','lightskyblue_2','lightskyblue_3','lightskyblue_4','skyblue_1','skyblue_2','skyblue_3','skyblue_4','skyblue','deepskyblue_1','deepskyblue','deepskyblue_2','deepskyblue_3','deepskyblue_4','peacock','lightblue','lightblue_1','lightblue_2','lightblue_3','lightblue_4','powderblue','cadetblue_1','cadetblue_2','cadetblue_3','cadetblue_4','turquoise_1','turquoise_2','turquoise_3','turquoise_4','cadetblue','darkturquoise','azure_1','azure','azure_2','azure_3','azure_4','lightcyan_1','lightcyan','lightcyan_2','lightcyan_3','lightcyan_4','paleturquoise_1','paleturquoise_2','paleturquoise','paleturquoise_3','paleturquoise_4','darkslategray','darkslategray_1','darkslategray_2','darkslategray_3','darkslategray_4','cyan','aqua','cyan_2','cyan_3','cyan_4','darkcyan','teal','mediumturquoise','lightseagreen','manganeseblue','turquoise','coldgrey','turquoiseblue','aquamarine_1','aquamarine','aquamarine_2','aquamarine_3','mediumaquamarine','aquamarine_4','mediumspringgreen','mintcream','springgreen','springgreen_1','springgreen_2','springgreen_3','mediumseagreen','seagreen_1','seagreen_2','seagreen_3','seagreen_4','seagreen','emeraldgreen','mint','cobaltgreen','honeydew_1','honeydew','honeydew_2','honeydew_3','honeydew_4','darkseagreen','darkseagreen_1','darkseagreen_2','darkseagreen_3','darkseagreen_4','palegreen','palegreen_1','palegreen_2','lightgreen','palegreen_3','palegreen_4','limegreen','forestgreen','green_1','lime','green_2','green_3','green_4','green','darkgreen','sapgreen','lawngreen','chartreuse_1','chartreuse','chartreuse_2','chartreuse_3','chartreuse_4','greenyellow','darkolivegreen_1','darkolivegreen_2','darkolivegreen_3','darkolivegreen_4','darkolivegreen','olivedrab','olivedrab_1','olivedrab_2','olivedrab_3','yellowgreen','olivedrab_4','ivory_1','ivory','ivory_2','ivory_3','ivory_4','beige','lightyellow_1','lightyellow','lightyellow_2','lightyellow_3','lightyellow_4','lightgoldenrodyellow','yellow_1','yellow','yellow_2','yellow_3','yellow_4','warmgrey','olive','darkkhaki','khaki_1','khaki_2','khaki_3','khaki_4','khaki','palegoldenrod','lemonchiffon_1','lemonchiffon','lemonchiffon_2','lemonchiffon_3','lemonchiffon_4','lightgoldenrod_1','lightgoldenrod_2','lightgoldenrod_3','lightgoldenrod_4','banana','gold_1','gold','gold_2','gold_3','gold_4','cornsilk_1','cornsilk','cornsilk_2','cornsilk_3','cornsilk_4','goldenrod','goldenrod_1','goldenrod_2','goldenrod_3','goldenrod_4','darkgoldenrod','darkgoldenrod_1','darkgoldenrod_2','darkgoldenrod_3','darkgoldenrod_4','orange_1','orange','orange_2','orange_3','orange_4','floralwhite','oldlace','wheat','wheat_1','wheat_2','wheat_3','wheat_4','moccasin','papayawhip','blanchedalmond','navajowhite_1','navajowhite','navajowhite_2','navajowhite_3','navajowhite_4','eggshell','tan_','brick','cadmiumyellow','antiquewhite','antiquewhite_1','antiquewhite_2','antiquewhite_3','antiquewhite_4','burlywood','burlywood_1','burlywood_2','burlywood_3','burlywood_4','bisque_1','bisque','bisque_2','bisque_3','bisque_4','melon','carrot','darkorange','darkorange_1','darkorange_2','darkorange_3','darkorange_4','orange','tan_1','tan_2','tan_3','peru','tan_4','linen','peachpuff_1','peachpuff','peachpuff_2','peachpuff_3','peachpuff_4','seashell_1','seashell','seashell_2','seashell_3','seashell_4','sandybrown','rawsienna','chocolate','chocolate_1','chocolate_2','chocolate_3','chocolate_4','saddlebrown','ivoryblack','flesh','cadmiumorange','burntsienna','sienna','sienna_1','sienna_2','sienna_3','sienna_4','lightsalmon_1','lightsalmon','lightsalmon_2','lightsalmon_3','lightsalmon_4','coral','orangered_1','orangered','orangered_2','orangered_3','orangered_4','sepia','darksalmon','salmon_1','salmon_2','salmon_3','salmon_4','coral_1','coral_2','coral_3','coral_4','burntumber','tomato_1','tomato','tomato_2','tomato_3','tomato_4','salmon','mistyrose_1','mistyrose','mistyrose_2','mistyrose_3','mistyrose_4','snow_1','snow','snow_2','snow_3','snow_4','rosybrown','rosybrown_1','rosybrown_2','rosybrown_3','rosybrown_4','lightcoral','indianred','indianred_1','indianred_2','indianred_4','indianred_3','brown','brown_1','brown_2','brown_3','brown_4','firebrick','firebrick_1','firebrick_2','firebrick_3','firebrick_4','red_1','red','red_2','red_3','red_4','darkred','maroon','sgi_beet','sgi_slateblue','sgi_lightblue','sgi_teal','sgi_chartreuse','sgi_olivedrab','sgi_brightgray','sgi_salmon','sgi_darkgray','sgi_gray_12','sgi_gray_16','sgi_gray_32','sgi_gray_36','sgi_gray_52','sgi_gray_56','sgi_lightgray','sgi_gray_72','sgi_gray_76','sgi_gray_92','sgi_gray_96','white','white_smoke','gray_96','gainsboro','lightgrey','silver','darkgray','gray','dimgray','gray_42','black','gray_99','gray_98','gray_97','white_smoke','gray_96','gray_95','gray_94','gray_93','gray_92','gray_91','gray_90','gray_89','gray_88','gray_87','gray_86','gray_85','gray_84','gray_83','gray_82','gray_81','gray_80','gray_79','gray_78','gray_77','gray_76','gray_75','gray_74','gray_73','gray_72','gray_71','gray_70','gray_69','gray_68','gray_67','gray_66','gray_65','gray_64','gray_63','gray_62','gray_61','gray_60','gray_59','gray_58','gray_57','gray_56','gray_55','gray_54','gray_53','gray_52','gray_51','gray_50','gray_49','gray_48','gray_47','gray_46','gray_45','gray_44','gray_43','gray_42','dimgray','gray_42','gray_40','gray_39','gray_38','gray_37','gray_36','gray_35','gray_34','gray_33','gray_32','gray_31','gray_30','gray_29','gray_28','gray_27','gray_26','gray_25','gray_24','gray_23','gray_22','gray_21','gray_20','gray_19','gray_18','gray_17','gray_16','gray_15','gray_14','gray_13','gray_12','gray_11','gray_10','gray_9','gray_8','gray_7','gray_6','gray_5','gray_4','gray_3','gray_2','gray_1'
ListCodes() = 'B0171F','DC143C','FFB6C1','FFAEB9','EEA2AD','CD8C95','8B5F65','FFC0CB','FFB5C5','EEA9B8','CD919E','8B636C','DB7093','FF82AB','EE799F','CD6889','8B475D','FFF0F5','FFF0F5','EEE0E5','CDC1C5','8B8386','FF3E96','EE3A8C','CD3278','8B2252','FF69B4','FF6EB4','EE6AA7','CD6090','8B3A62','872657','FF1493','FF1493','EE1289','CD1076','8B0A50','FF34B3','EE30A7','CD2990','8B1C62','C71585','D02090','DA70D6','FF83FA','EE7AE9','CD69C9','8B4789','D8BFD8','FFE1FF','EED2EE','CDB5CD','8B7B8B','FFBBFF','EEAEEE','CD96CD','8B668B','DDA0DD','EE82EE','FF00FF','FF00FF','EE00EE','CD00CD','8B008B','8B008B','800080','BA55D3','E066FF','D15FEE','B452CD','7A378B','9400D3','9932CC','BF3EFF','B23AEE','9A32CD','68228B','4B0082','8A2BE2','9B30FF','912CEE','7D26CD','551A8B','9370DB','AB82FF','9F79EE','8968CD','5D478B','483D8B','8470FF','7B68EE','6A5ACD','836FFF','7A67EE','6959CD','473C8B','F8F8FF','E6E6FA','0000FF','0000EE','0000CD','0000CD','00008B','00008B','000080','191970','3D59AB','4169E1','4876FF','436EEE','3A5FCD','27408B','6495ED','B0C4DE','CAE1FF','BCD2EE','A2B5CD','6E7B8B','778899','708090','C6E2FF','B9D3EE','9FB6CD','6C7B8B','1E90FF','1E90FF','1C86EE','1874CD','104E8B','F0F8FF','4682B4','63B8FF','5CACEE','4F94CD','36648B','87CEFA','B0E2FF','A4D3EE','8DB6CD','607B8B','87CEFF','7EC0EE','6CA6CD','4A708B','87CEEB','00BFFF','00BFFF','00B2EE','009ACD','00688B','33A1C9','ADD8E6','BFEFFF','B2DFEE','9AC0CD','68838B','B0E0E6','98F5FF','8EE5EE','7AC5CD','53868B','00F5FF','00E5EE','00C5CD','00868B','5F9EA0','00CED1','F0FFFF','F0FFFF','E0EEEE','C1CDCD','838B8B','E0FFFF','E0FFFF','D1EEEE','B4CDCD','7A8B8B','BBFFFF','AEEEEE','AEEEEE','96CDCD','668B8B','2F4F4F','97FFFF','8DEEEE','79CDCD','528B8B','00FFFF','00FFFF','00EEEE','00CDCD','008B8B','008B8B','008080','48D1CC','20B2AA','03A89E','40E0D0','808A87','00C78C','7FFFD4','7FFFD4','76EEC6','66CDAA','66CDAA','458B74','00FA9A','F5FFFA','00FF7F','00EE76','00CD66','008B45','3CB371','54FF9F','4EEE94','43CD80','2E8B57','2E8B57','00C957','BDFCC9','3D9140','F0FFF0','F0FFF0','E0EEE0','C1CDC1','838B83','8FBC8F','C1FFC1','B4EEB4','9BCD9B','698B69','98FB98','9AFF9A','90EE90','90EE90','7CCD7C','548B54','32CD32','228B22','00FF00','00FF00','00EE00','00CD00','008B00','008000','006400','308014','7CFC00','7FFF00','7FFF00','76EE00','66CD00','458B00','ADFF2F','CAFF70','BCEE68','A2CD5A','6E8B3D','556B2F','6B8E23','C0FF3E','B3EE3A','9ACD32','9ACD32','698B22','FFFFF0','FFFFF0','EEEEE0','CDCDC1','8B8B83','F5F5DC','FFFF00','FFFF00','EEEED1','CDCDB4','8B8B7A','FAFAD2','FFFF00','FFFF00','EEEE00','CDCD00','8B8B00','808069','808000','BDB76B','FFF68F','EEE685','CDC673','8B864E','F0E68C','EEE8AA','FFFACD','FFFACD','EEE9BF','CDC9A5','8B8970','FFEC8B','EEDC82','CDBE70','8B814C','E3CF57','FFD700','FFD700','EEC900','CDAD00','8B7500','FFF8DC','FFF8DC','EEE8CD','CDC8B1','8B8878','DAA520','FFC125','EEB422','CD9B1D','8B6914','B8860B','FFB90F','EEAD0E','CD950C','8B6508','FFA500','FFA500','EE9A00','CD8500','8B5A00','FFFAF0','FDF5E6','F5DEB3','FFE7BA','EED8AE','CDBA96','8B7E66','FFE4B5','FFEFD5','FFEBCD','FFDEAD','FFDEAD','EECFA1','CDB38B','8B795E','FCE6C9','D2B48C','9C661F','FF9912','FAEBD7','FFEFDB','EEDFCC','CDC0B0','8B8378','DEB887','FFD39B','EEC591','CDAA7D','8B7355','FFE4C4','FFE4C4','EED5B7','CDB79E','8B7D6B','E3A869','ED9121','FF8C00','FF7F00','EE7600','CD6600','8B4500','FF8000','FFA54F','EE9A49','CD853F','CD853F','8B5A2B','FAF0E6','FFDAB9','FFDAB9','EECBAD','CDAF95','8B7765','FFF5EE','FFF5EE','EEE5DE','CDC5BF','8B8682','F4A460','C76114','D2691E','FF7F24','EE7621','CD661D','8B4513','8B4513','292421','FF7D40','FF6103','8A360F','A0522D','FF8247','EE7942','CD6839','8B4726','FFA07A','FFA07A','EE9572','CD8162','8B5742','FF7F50','FF4500','FF4500','EE4000','CD3700','8B2500','5E2612','E9967A','FF8C69','EE8262','CD7054','8B4C39','FF7256','EE6A50','CD5B45','8B3E2F','8A3324','FF6347','FF6347','EE5C42','CD4F39','8B3626','FA8072','FFE4E1','FFE4E1','EED5D2','CDB7B5','8B7D7B','FFFAFA','FFFAFA','EEE9E9','CDC9C9','8B8989','BC8F8F','FFC1C1','EEB4B4','CD9B9B','8B6969','F08080','CD5C5C','FF6A6A','EE6363','8B3A3A','CD5555','A52A2A','FF4040','EE3B3B','CD3333','8B2323','B22222','FF3030','EE2C2C','CD2626','8B1A1A','FF0000','FF0000','EE0000','CD0000','8B0000','8B0000','800000','8E388E','7171C6','7D9EC0','388E8E','71C671','8E8E38','C5C1AA','C67171','555555','1E1E1E','282828','515151','5B5B5B','848484','8E8E8E','AAAAAA','B7B7B7','C1C1C1','EAEAEA','F4F4F4','FFFFFF','F5F5F5','F5F5F5','DCDCDC','D3D3D3','C0C0C0','A9A9A9','808080','696969','696969','000000','FCFCFC','FAFAFA','F7F7F7','F5F5F5','F5F5F5','F2F2F2','F0F0F0','EDEDED','EBEBEB','E8E8E8','E5E5E5','E3E3E3','E0E0E0','DEDEDE','DBDBDB','D9D9D9','D6D6D6','D4D4D4','D1D1D1','CFCFCF','CCCCCC','C9C9C9','C7C7C7','C4C4C4','C2C2C2','BFBFBF','BDBDBD','BABABA','B8B8B8','B5B5B5','B3B3B3','B0B0B0','ADADAD','ABABAB','A8A8A8','A6A6A6','A3A3A3','A1A1A1','9E9E9E','9C9C9C','999999','969696','949494','919191','8F8F8F','8C8C8C','8A8A8A','878787','858585','828282','7F7F7F','7D7D7D','7A7A7A','787878','757575','737373','707070','6E6E6E','6B6B6B','696969','696969','666666','636363','616161','5E5E5E','5C5C5C','595959','575757','545454','525252','4F4F4F','4D4D4D','4A4A4A','474747','454545','424242','404040','3D3D3D','3B3B3B','383838','363636','333333','303030','2E2E2E','2B2B2B','292929','262626','242424','212121','1F1F1F','1C1C1C','1A1A1A','171717','141414','121212','0F0F0F','0D0D0D','0A0A0A','080808','050505','030303'
for i = 1 to count ListColours
  (ListColours(i)) = '(ListCodes(i))'

# ------------------------------------------------------------------------------------------------------------------------------------
##This section is for visualization, unnecessary.
#
## load the list of mutations, assume defined.
##LOADTAB (MacroTargetB)_WOW_listMutationsEasyReadable
##Raw() = TAB 1
##totalColumns = count Raw
##totalColumns = (totalColumns) / 3
#
## create an easy to inspect style
##STYLE tube
##BALLSTICKRES ALL
##COLORATOM element C, (seagreen)
##COLORATOM res sub element C, (gold)
##SHOWRES all with distance < 4 from res sub
#
##for i = 1 to totalColumns
##  SHOWRES protein res (0+(Raw(( 3*((i)-1) ) + 2)))
##  SHOWRES all with distance < 3 from protein res (0+(Raw(( 3*((i)-1) ) + 2)))
##  COLORATOM protein res (0+(Raw(( 3*((i)-1) ) + 2))) element C, (salmon)
##  LABELRES  protein res (0+(Raw(( 3*((i)-1) ) + 2))), (Raw(( 3*((i)-1) ) + 1))(0+(Raw(( 3*((i)-1) ) + 2)))(Raw(( 3*((i)-1) ) + 3)), height=0.8, color=black, z=-1  
#
## --------------------------------------------------------------------------------------------------------------------------------

## HERE IS A FIX
## problem is that Yasara renames all the atoms after adding a hydrogen atom. Therefore first store the atom names and later give them back. ANOTHER PROBLEM WITH PRIMARY AMINES NOT ADRESSED HERE IS THAT THE 2ND hydrogen atom is now also called H99. 

ListHydrogenAtomNames() = LISTATOM res SUB element H, FORMAT=ATOMNAME
PRINT (ListHydrogenAtomNames)

# do not forget to clean up the structure a bit
Renamemol MOL X with minimum distance from MOL A res lys 285, A
Renamemol MOL X with minimum distance from MOL B res lys 285, B

#Make PLP aromatic
subunit='A','B'
for i=1 to 2
  # Fix H95, make it look more sp2
  DELBOND mol (subunit(i)) res SUB atom N99, mol (subunit(i)) res SUB atom C99
  Dihedral MOL (subunit(i)) RES SUB ATOM C4, MOL (subunit(i)) RES SUB ATOM C50, MOL (subunit(i)) RES SUB ATOM N99, MOL (subunit(i)) RES SUB ATOM H95,SET=0
  ADDBOND mol (subunit(i)) res SUB atom N99, mol (subunit(i)) res SUB atom C99, 1  
  # Fix H5, make it look more sp2
  DELBOND mol (subunit(i)) res SUB atom N99, mol (subunit(i)) res SUB atom C50
  Dihedral MOL (subunit(i)) RES SUB ATOM C6, MOL (subunit(i)) RES SUB ATOM C4, MOL (subunit(i)) RES SUB ATOM C50, MOL (subunit(i)) RES SUB ATOM H5,SET=0
  ADDBOND mol (subunit(i)) res SUB atom N99, mol (subunit(i)) res SUB atom C50, 2

  # Make ring aromatic
  ADDBOND mol (subunit(i)) res SUB atom C50, mol (subunit(i)) res SUB atom C4, 1
  ADDBOND mol (subunit(i)) res SUB atom C50, mol (subunit(i)) res SUB atom N99, 2
  ADDBOND mol (subunit(i)) res SUB atom C4, mol (subunit(i)) res SUB atom C3, 1.5
  ADDBOND mol (subunit(i)) res SUB atom C1, mol (subunit(i)) res SUB atom C3, 1.5
  ADDBOND mol (subunit(i)) res SUB atom C1, mol (subunit(i)) res SUB atom N50, 1.5
  ADDBOND mol (subunit(i)) res SUB atom N50, mol (subunit(i)) res SUB atom C7, 1.5
  ADDBOND mol (subunit(i)) res SUB atom C7, mol (subunit(i)) res SUB atom C6, 1.5
  ADDBOND mol (subunit(i)) res SUB atom C6, mol (subunit(i)) res SUB atom C4, 1.5

  # For some substrates, e.g. 47R, yasara adds a covalent bond between O5 of PO4 and an atom of the substrate itself. Correct this.
  # Rare instance.
  PhosphateAtoms = 'P1 O2 O3 O4 O5'
  AtomsCloseToPhosphate()= LISTATOM mol (subunit(i)) res SUB with distance < 3 from mol (subunit(i)) res SUB atom P1 and not (PhosphateAtoms)
  if (count AtomsCloseToPhosphate) > 0.5
    PRINT WARNING (count AtomsCloseToPhosphate) atoms found to be too close to the phosphate of PLP. Currently reassigning bond orders. Beware.
    for j=1 to count AtomsCloseToPhosphate
      DELBOND mol (subunit(i)) res SUB atom O5, MOL (subunit(i)) res SUB atom (AtomsCloseToPhosphate(j))
      DELBOND mol (subunit(i)) res SUB atom O4, MOL (subunit(i)) res SUB atom (AtomsCloseToPhosphate(j))
      DELBOND mol (subunit(i)) res SUB atom O3, MOL (subunit(i)) res SUB atom (AtomsCloseToPhosphate(j))
      # MAKE PO4 RESONANT AGAIN
      ADDBOND mol (subunit(i)) res SUB atom O3, MOL (subunit(i)) res SUB atom P1, order=1.33, update=no
      ADDBOND mol (subunit(i)) res SUB atom O4, MOL (subunit(i)) res SUB atom P1, order=1.33, update=no
      ADDBOND mol (subunit(i)) res SUB atom O5, MOL (subunit(i)) res SUB atom P1, order=1.33, update=no
  else
    PRINT No atoms found within 3 Angstrom of res SUB atom P1, no bond order reassigned

# Delete water molecules that are too close to the substrate
DELRES res HOH with distance < 0.7 from res SUB element C O N

# Add atom H99 back to structure
ADDHYDATOM MOL A res sub atom C99, 1,update=no
ADDHYDATOM MOL B res sub atom C99, 1,update=no
DelAtom MOL A res lys 285 atom HZ with minimum distance from res sub atom H99
DelAtom MOL B res lys 285 atom HZ with minimum distance from res sub atom H99

# some cleaning up
COLORBONDS order
HIDEATOM element H with bond to atom element C

SAVEYOB 3, (MacroTargetB)_WOW.yob
SAVEPDB 3, (MacroTargetB)_forPymol.pdb

EXIT
