#!/bin/bash
#SBATCH --time=23:59:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8gb
#SBATCH --job-name=QM-01R
#SBATCH --partition=nodes


module load    Gaussian/09-D.01-GaussView-5.0.9
srun g09 01R.com 01R.out
